### ISSUE TITLE
Should the __name__ Label for Counter metrics always end in "_total"

### ISSUE THREAD

**Issue by Aneurysm9** [prometheus/compliance#19]
While working on some of the OTel Collector test failures I found the [PRW exporter ensuring](https://github.com/open-telemetry/opentelemetry-collector/pull/2993) that the `__name__` attribute for all counter metrics ended in "_total" if it existed.  This definitely doesn't seem to be expected by these compliance tests, given the counter test uses [a counter with no suffix](https://github.com/prometheus/compliance/blob/main/remote_write/cases/counter.go#L17) and [asserts that its `__name__` label also has no suffix](https://github.com/prometheus/compliance/blob/main/remote_write/cases/counter.go#L29).  

That said, there [are](https://github.com/prometheus/client_python/issues/317) [indications](https://github.com/prometheus/client_golang/blob/0400fc44d42dd0bca7fb16e87ea0313bb2eb8c53/prometheus/testutil/promlint/promlint_test.go#L444) that counter `__name__` attributes should always end in "_total".  Is this a requirement?  If so is it the responsibility of the client to ensure it is satisfied? The receiver? The remote write exporter? Any guidance and advice is appreciated.

**Comment by tomwilkie** [comment]
Hi @Aneurysm9! Sorry for the slow reply, I missed this.

> That said, there are indications that counter __name__ attributes should always end in "_total". Is this a requirement?

The naming requirements are not enforced, no - there are plenty of misnamed metrics out there and we need agents to correctly propagate them.

> If so is it the responsibility of the client to ensure it is satisfied? The receiver? The remote write exporter? 

We've discussed this and I think with the move to open metrics the client libraries will probably start enforcing this themselves - but we need to be really careful about backwards compatibility here, so we're not doing anything in a rush.
