### ISSUE TITLE
Allow bringing your own binary for a runner

### ISSUE THREAD

**Issue by rakyll** [prometheus/compliance#5]
When doing active development, we need to run the compliance tests against a development version. If a runner allows to test against a local binary when configured, it'd be a great improvement.

**Comment by tomwilkie** [comment]
This is possible with a little hidden behaviour: the test suite downloads builds and sticks them in the `bin/` dir - and doesn't bother to do the download again if the file exists.  I tend to stick my build-under-test in that dir:

https://github.com/tomwilkie/remote-write-compliance/blob/main/targets/common.go#L62
